permalink: pretty
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:categories/:title
baseurl: 'http://elenijr.net'
prose:
  rooturl: '_posts'
  siteurl: 'http://elenijr.net'
  relativeLinks: 'http://elenijr.net/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          help: "Select a category for this post."
          element: "select"
          options: ["blog", "recipe", "review"]
      - name: "layout"
        field:
          element: "select"
          help: "Select the layout for the post."
          options: ["blog", "recipe"]
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Greece"
              value: "greece"
            - name: "Peru"
              value: "Peru"
            - name: "Eggplant"
              value: "eggplant"
      - name: "servings"
        field:
          element: "text"
          label: "Servings"
      - name: "time"
        field:
          element: "text"
          label: "Cook/Prep Time"
          help: "Add info about the cooking/prep time for this recipe."
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
