permalink: pretty
markdown: rdiscount
baseurl: 'http://elenijr.net'
prose:
  rooturl: '_posts'
  siteurl: 'http://elenijr.net'
  relativeLinks: 'http://elenijr.net/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Greece"
              value: "greece"
            - name: "Peru"
              value: "Peru"
            - name: "Eggplant"
              value: "eggplant"
    _posts/recipe:
      - name: "category"
        field:
          element: "hidden"
          value: "recipe"
      - name: "layout"
        field:
          element: "hidden"
          value: "recipe"
      - name: "servings"
        field:
          element: "number"
          label: "Servings"
          value: ""
      - name: "ingredients"
        field:
          element: "textarea"
          value: ""
          label: "Ingredients for recipe"
          help: "List the ingredients for the recipe. Use an unordered list if possible."
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
