# Site settings
title: Tzunior's Table
email: your-email@domain.com
description: "A place to hang out and explore Proustian moments in food and cooking."
baseurl: "http://elenijr.net"
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
permalink: /:categories/:title

