title: Tzunior's Table
email: hello@elenijr.net
description: "A place to hang out and explore Proustian moments in food and cooking."
baseurl: "http://elenijr.net"
url: "http://elenijr.net"
twitter: elenijr
markdown: kramdown
permalink: pretty
permalink: /:categories/:title
gems:
  - jekyll-sitemap

# Prose
prose:
  rooturl: '_posts'
  siteurl: 'http://elenijr.net'
  relativeLinks: 'http://elenijr.net/links.jsonp'
  media: 'media'
  metadata:
    _posts/recipe:
      - name: "category"
        field:
          element: "hidden"
          value: "recipe"
      - name: "layout"
        field:
          element: "hidden"
          value: "recipe"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "teaser"
        field:
          element: "text"
          label: "Teaser"
          value: ""
          help: "Enter 1-2 sentences to use as a teaser for this post."
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Greece"
              value: "greece"
            - name: "Peru"
              value: "Peru"
            - name: "Eggplant"
              value: "eggplant"
      - name: "flickr"
        field:
          element: "text"
          label: "Flickr Photoset ID"
          value: ""
      - name: "servings"
        field:
          element: "text"
          label: "Servings"
      - name: "time"
        field:
          element: "text"
          label: "Cook/Prep Time"
          help: "Add info about the cooking/prep time for this recipe."
      - name: "ingredient_1"
        field:
          element: "text"
          label: "Ingredient #1"
      - name: "ingredient_2"
        field:
          element: "text"
          label: "Ingredient #2"
      - name: "ingredient_3"
        field:
          element: "text"
          label: "Ingredient #3"
      - name: "ingredient_4"
        field:
          element: "text"
          label: "Ingredient #4"
      - name: "ingredient_5"
        field:
          element: "text"
          label: "Ingredient #5"
      - name: "ingredient_6"
        field:
          element: "text"
          label: "Ingredient #6"
      - name: "ingredient_7"
        field:
          element: "text"
          label: "Ingredient #7"
      - name: "ingredient_8"
        field:
          element: "text"
          label: "Ingredient #8"
      - name: "ingredient_9"
        field:
          element: "text"
          label: "Ingredient #9"
      - name: "ingredient_10"
        field:
          element: "text"
          label: "Ingredient #10"
      - name: "ingredient_11"
        field:
          element: "text"
          label: "Ingredient #11"
      - name: "ingredient_12"
        field:
          element: "text"
          label: "Ingredient #12"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Allow comments for this post?"
          value: true
    _posts/post:
      - name: "category"
        field:
          help: "Select a category for this post."
          element: "select"
          options: ["post", "review"]
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "teaser"
        field:
          element: "text"
          label: "Teaser"
          value: ""
          help: "Enter 1-2 sentences to use as a teaser for this post."
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Greece"
              value: "greece"
            - name: "Peru"
              value: "Peru"
            - name: "Eggplant"
              value: "eggplant"
      - name: "flickr"
        field:
          element: "text"
          label: "Flickr Photoset ID"
          value: ""
      - name: "comments"
        field:
          element: "checkbox"
          label: "Allow comments for this post?"
          value: true
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "comments"
        field:
          element: "checkbox"
          label: "Allow comments for this post?"
          value: false
